tags:
  - name: users
    description: users API

paths:
  # [GET] users/id
  /users/{id}:
    get:
      tags:
        - users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

# definitions
definitions:
  users:
    type: object
    required:
      - userName
      - password
    properties:
      userName:
        type: string
        description: user Name
      password:
        type: string
        description: user Password

schemes:
  - https
  - http
